version: '3.9'

services:
  app:
    image: mcr.microsoft.com/devcontainers/python:3.11
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - PIP_DISABLE_PIP_VERSION_CHECK=1
    working_dir: /workspace

  db:
    image: postgres:15
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456

volumes:
  postgres_data:
