-- Active: 1749757574490@@127.0.0.1@5432@reserva

-- VERSAO: 3.1 beta
-- REMODELAGEM PARA SEPARAR SALA FÍSICA DA DISPONIBILIDADE POR TURNO/PERIODO AINDA EM ANDAMENTO!

-- Criação da tabela Diretor
CREATE TABLE diretor (
    iddiretor INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY, /* essa é a forma correta de usar o autoincremnto a partir da decima versão do postgres*/
    cpf CHAR(11) NOT NULL UNIQUE,
    copfdt CHAR(11), -- NULLABLE
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL,
    senha VARCHAR(255) NOT NULL,
    dthinsart TIMESTAMP DEFAULT NOW(),
    dthdelete TIMESTAMP CHECK (dthdelete >= dthinsart OR dthdelete IS NULL), -- NULLABLE INICIALMENTE CRIAR REGRA DE NEGÓCIO PARA QUANDO O STATUS FOR FALSE E AQUI TER DADOS
    status BOOLEAN DEFAULT TRUE -- PARA DELETE LÓGICO
);


/*
    OBSERVAÇÕES:

        Temos três formas de criar um AUTOINCREMENT no POSTGRES:
         
        - INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY -> mais recomendado a partir da decima versão

            Se for GENERATED ALWAYS AS IDENTITY PRIMARY KEY ->   O banco sempre gera o valor (você não pode inserir manualmente). É AUTOMÁTICO

            Se for GENERATED BY DEFAULT AS IDENTITY -> O banco gera automaticamente, mas você pode sobrescrever com um valor manual, se quiser.

        - SERIAL PRIMARY KEY ->  um atalho, mas não é uma palavra reservada oficialmente — é amplamente usada e funciona bem, mas é menos explícita que IDENTITY.

        - CREATE SEQUENCE usuarios_id_seq; -> Controle totalmente manual 

            exemplo: 

            CREATE SEQUENCE usuarios_id_seq;

                CREATE TABLE usuarios (
                    id INTEGER PRIMARY KEY DEFAULT nextval('usuarios_id_seq'),
                    nome TEXT NOT NULL
                );
*/


-- Criação da tabela assessora
CREATE TABLE assessora (
    idassessora INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    cpfdt CHAR(11), -- NULLABLE
    cpfass CHAR(11), -- NULLABLE
    cpf CHAR(11) NOT NULL UNIQUE,
    nome VARCHAR(50) NOT NULL, 
    email VARCHAR(100) NOT NULL,
    senha VARCHAR(255) NOT NULL,
    dthinsart TIMESTAMP DEFAULT NOW(),
    dthdelete TIMESTAMP CHECK (dthdelete >= dthinsart OR dthdelete IS NULL), -- NULLABLE INICIALMENTE CRIAR REGRA DE NEGÓCIO PARA QUANDO O STATUS FOR FALSE E AQUI TER DADOS 
    FOREIGN KEY (cpfdt) REFERENCES diretor(cpf),
    FOREIGN KEY (cpfass) REFERENCES assessora(cpf),
    status BOOLEAN DEFAULT TRUE -- PARA FAZER DELETE LÓGICO

);

-- Criação de tabela NTI 
CREATE TABLE nti (
    idnti INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    cpfnti CHAR(11), 
    cpf CHAR(11) NOT NULL UNIQUE,
    nome VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL,
    senha VARCHAR(255) NOT NULL,
    dthinsart TIMESTAMP DEFAULT NOW(),
    dthdelete TIMESTAMP CHECK (dthdelete >= dthinsart OR dthdelete IS NULL), -- NULLABLE INICIALMENTE CRIAR REGRA DE NEGÓCIO PARA QUANDO O STATUS FOR FALSE E AQUI TER DADOS 
    FOREIGN KEY (cpfnti) REFERENCES nti(cpf),
    status BOOLEAN DEFAULT TRUE -- PARA FAZER DELETE LÓGICO
);

-- Criação de tabela Turma
CREATE TABLE turma(
    idturma INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    cpfnti CHAR(11), -- NULABLE
    codturma VARCHAR(100) NOT NULL,
    periodoletivo VARCHAR(15) NOT NULL,
    dthinsart TIMESTAMP DEFAULT NOW(),
    dthdelete TIMESTAMP CHECK (dthdelete >= dthinsart OR dthdelete IS NULL), -- NULLABLE INICIALMENTE CRIAR REGRA DE NEGÓCIO PARA QUANDO O STATUS FOR FALSE E AQUI TER DADOS 
    FOREIGN KEY (cpfnti) REFERENCES nti(cpf),
    status BOOLEAN DEFAULT TRUE -- DELETE LÓGICO
);

-- Criação de tabela sala (representa a sala física)
CREATE TABLE sala(
    idsala INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    cpfnti CHAR(11), -- NULLABLE 
    bloco CHAR(1) NOT NULL,
    tvtamanho INT,
    datashow BOOLEAN DEFAULT TRUE,
    capacidade INT NOT NULL,
    andar VARCHAR(25) NOT NULL,
    numerosala INT NOT NULL,
    dthinsart TIMESTAMP DEFAULT NOW(),
    dthdelete TIMESTAMP CHECK (dthdelete >= dthinsart OR dthdelete IS NULL), -- NULLABLE INICIALMENTE CRIAR REGRA DE NEGÓCIO PARA QUANDO O STATUS FOR FALSE E AQUI TER DADOS 
    FOREIGN KEY (cpfnti) REFERENCES nti(cpf),
    status BOOLEAN NOT NULL DEFAULT TRUE -- DELETE LÓGICO
);

--Criação da tabela tusala (para facilicar o link entre sala e turma)

CREATE TABLE tusala (
    idtursala INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    idsala INT NOT NULL,
    idturma INT NOT NULL,
    FOREIGN KEY (idsala) REFERENCES sala(idsala),
    FOREIGN KEY (idturma) REFERENCES turma(idturma)
);


-- Criação da tabela sala_disponibilidade (turno + período para cada sala)
CREATE TABLE saladispo (
    idsaladispo INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    idsala INT NOT NULL,
    periodo VARCHAR(15) NOT NULL CHECK (periodo IN ('Primeiro', 'Segundo', 'Ambos')),
    turno VARCHAR(10) CHECK (turno IN ('Manhã', 'Tarde', 'Noite') OR turno IS NULL),
    disponibilidade BOOLEAN NOT NULL DEFAULT TRUE,
    dthinsart TIMESTAMP DEFAULT NOW(),
    dthdelete TIMESTAMP CHECK (dthdelete >= dthinsart OR dthdelete IS NULL), -- NULLABLE INICIALMENTE CRIAR REGRA DE NEGÓCIO PARA QUANDO O STATUS FOR FALSE E AQUI TER DADOS 
    status BOOLEAN NOT NULL DEFAULT TRUE, -- DELETE LÓGICO
    FOREIGN KEY (idsala) REFERENCES sala(idsala)
);


-- Criação da tabela reserva (ligada à sala_disponibilidade)
CREATE TABLE reserva(
    idreserva INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    cpddt CHAR(11), -- NULLABLE PODE SER DIRETOR
    cpfass CHAR(11), -- NULLABLE PODE SER ASSESSORA
    cpfnti CHAR(11), -- NULLABLE PODE SER NTI
    idsaladispo INT NOT NULL,
    idturma INT NULL, -- NULLABLE PODEMOS USAR FUTURAMENTE PARA LISTAR TURMAS JÁ CADASTRADAS
    codturma VARCHAR(100) NOT NULL, -- Apenas informativo
    diasemana VARCHAR(15) NOT NULL CHECK (diasemana IN ('Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta', 'Sábado')),
    datainicial DATE DEFAULT CURRENT_DATE,
    datafinal DATE NOT NULL CHECK (datafinal >= datainicial),
    responsavel VARCHAR(100) NOT NULL,
    descricao VARCHAR(255),
    situacao BOOLEAN DEFAULT TRUE NOT NULL, -- TRUE = Reservado, FALSE = Livre
    dthinsart TIMESTAMP DEFAULT NOW(),
    dthdelete TIMESTAMP CHECK (dthdelete >= dthinsart OR dthdelete IS NULL), -- NULLABLE INICIALMENTE CRIAR REGRA DE NEGÓCIO PARA QUANDO O STATUS FOR FALSE E AQUI TER DADOS 
    FOREIGN KEY (cpfass) REFERENCES assessora(cpf),
    FOREIGN KEY (cpfnti) REFERENCES nti(cpf),
    FOREIGN KEY (idsaladispo) REFERENCES saladispo(idsaladispo),
    FOREIGN KEY (idturma) REFERENCES turma(idturma),
    status BOOLEAN DEFAULT TRUE -- DELETE LÓGICO
);
