services:
  postgres:
    image: postgres:16-ALPINE
    ports: 
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${reserva}
      POSTGRES_USER: ${vitor}
      POSTGRES_PASSWORD: ${123456}
    deploy:
      resources:
        limits:
          cpus: '2'
          memorys: 512M
volumes:
  postgres_data:
