# Generated by Django 5.2.1 on 2025-06-11 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('idagendamento', models.AutoField(primary_key=True, serialize=False)),
                ('confirmsec', models.BooleanField(blank=True, null=True)),
                ('dthconfirmsec', models.DateTimeField(blank=True, null=True)),
                ('confirmresp', models.BooleanField(blank=True, null=True)),
                ('dthconfirmresp', models.DateTimeField(blank=True, null=True)),
                ('confirmcoord', models.BooleanField(blank=True, null=True)),
                ('dthconfirmcoord', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'agendamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Anamnese',
            fields=[
                ('idanamnese', models.AutoField(primary_key=True, serialize=False)),
                ('anamnesedoc', models.BinaryField(blank=True, null=True)),
                ('dthanexo', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'anamnese',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Arqinscrito',
            fields=[
                ('idarqinscrito', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(blank=True, null=True)),
                ('dtharquinscrito', models.DateTimeField()),
            ],
            options={
                'db_table': 'arqinscrito',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Arquivamento',
            fields=[
                ('idarquivamento', models.AutoField(primary_key=True, serialize=False)),
                ('idsolicitacao', models.IntegerField()),
                ('dtharq', models.DateTimeField(blank=True, null=True)),
                ('retencao', models.DateTimeField(blank=True, null=True)),
                ('justificativa', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'arquivamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Coordenador',
            fields=[
                ('idcoordenador', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('senha', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('crp', models.IntegerField(unique=True)),
                ('dthcoord', models.DateTimeField()),
                ('emailinst', models.CharField(max_length=255)),
                ('status', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'coordenador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Disponibilidade',
            fields=[
                ('iddisponibilidade', models.AutoField(primary_key=True, serialize=False)),
                ('manha', models.BooleanField(blank=True, null=True)),
                ('tarde', models.BooleanField(blank=True, null=True)),
                ('noite', models.BooleanField(blank=True, null=True)),
                ('sabado', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'disponibilidade',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Doencafisica',
            fields=[
                ('iddoencafisica', models.AutoField(primary_key=True, serialize=False)),
                ('doencaresp', models.BooleanField(blank=True, null=True)),
                ('cancer', models.BooleanField(blank=True, null=True)),
                ('diabete', models.BooleanField(blank=True, null=True)),
                ('disfusexual', models.BooleanField(blank=True, null=True)),
                ('doencadgt', models.BooleanField(blank=True, null=True)),
                ('escleorosemlt', models.BooleanField(blank=True, null=True)),
                ('hcpt', models.BooleanField(blank=True, null=True)),
                ('luposatm', models.BooleanField(blank=True, null=True)),
                ('obesidade', models.BooleanField(blank=True, null=True)),
                ('pblmarenal', models.BooleanField(blank=True, null=True)),
                ('outro', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'doencafisica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('idendereco', models.AutoField(primary_key=True, serialize=False)),
                ('cidade', models.CharField(max_length=40)),
                ('bairro', models.CharField(blank=True, max_length=50, null=True)),
                ('rua', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 'endereco',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Escolheins',
            fields=[
                ('idescolheins', models.AutoField(primary_key=True, serialize=False)),
                ('idfichacomunidade', models.IntegerField(blank=True, null=True)),
                ('status', models.BooleanField(blank=True, null=True)),
                ('dthescolha', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'escolheins',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estagiario',
            fields=[
                ('idestagiario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('ra', models.IntegerField(unique=True)),
                ('senha', models.CharField(max_length=10)),
                ('nivelestagio', models.CharField(max_length=10)),
                ('semestre', models.CharField(max_length=10)),
                ('emailinst', models.CharField(max_length=255)),
                ('dthestg', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'estagiario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fichafreqest',
            fields=[
                ('idfichafreq', models.AutoField(primary_key=True, serialize=False)),
                ('fichafreq', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fichafreqest',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Folhaevo',
            fields=[
                ('idfolhaevolucao', models.AutoField(primary_key=True, serialize=False)),
                ('idprontuario', models.IntegerField()),
                ('folhaevolucao', models.BinaryField()),
                ('dthanexo', models.DateTimeField()),
            ],
            options={
                'db_table': 'folhaevo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Htocorrencia',
            fields=[
                ('idhtc', models.AutoField(primary_key=True, serialize=False)),
                ('nomepessoa', models.CharField(max_length=50)),
                ('dthora', models.DateTimeField()),
                ('comparecimento', models.BooleanField(blank=True, null=True)),
                ('faltas', models.IntegerField()),
                ('justificativa', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'htocorrencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inscritocomunidade',
            fields=[
                ('idfichacomunidade', models.AutoField(primary_key=True, serialize=False)),
                ('nomeinscrito', models.CharField(max_length=100)),
                ('dtnascimento', models.DateField()),
                ('nomeresp', models.CharField(blank=True, max_length=50, null=True)),
                ('grauresp', models.CharField(blank=True, max_length=25, null=True)),
                ('cpfresp', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('estadocivilresp', models.CharField(blank=True, max_length=25, null=True)),
                ('tellcellresp', models.CharField(blank=True, max_length=20, null=True)),
                ('emailresp', models.CharField(blank=True, max_length=45, null=True)),
                ('estadocivilinscrito', models.CharField(blank=True, max_length=25, null=True)),
                ('cpfinscrito', models.CharField(max_length=11, unique=True)),
                ('tellcellinscrito', models.CharField(max_length=20)),
                ('contatourgencia', models.CharField(max_length=15)),
                ('emailinscrito', models.CharField(max_length=45)),
                ('identidadegenero', models.CharField(max_length=25)),
                ('etnia', models.CharField(max_length=15)),
                ('religiao', models.CharField(max_length=30)),
                ('confirmlgpd', models.BooleanField()),
                ('dthinscricao', models.DateField()),
                ('status', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inscritocomunidade',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inscritoconvenio',
            fields=[
                ('idfichaconvenio', models.AutoField(primary_key=True, serialize=False)),
                ('nomeinscrito', models.CharField(max_length=100)),
                ('dtnascimento', models.DateField()),
                ('testavpsico', models.BooleanField()),
                ('tipoencaminhamento', models.CharField(max_length=50)),
                ('nomeresp', models.CharField(blank=True, max_length=50, null=True)),
                ('grauresp', models.CharField(blank=True, max_length=25, null=True)),
                ('cpfresp', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('estadocivilresp', models.CharField(blank=True, max_length=25, null=True)),
                ('tellcellresp', models.CharField(blank=True, max_length=20, null=True)),
                ('emailresp', models.CharField(blank=True, max_length=45, null=True)),
                ('estadocivilinscrito', models.CharField(blank=True, max_length=25, null=True)),
                ('cpfinscrito', models.CharField(max_length=11, unique=True)),
                ('tellcellinscrito', models.CharField(max_length=20)),
                ('nomecontatourgencia', models.CharField(max_length=15)),
                ('emailinscrito', models.CharField(max_length=50)),
                ('identidadegenero', models.CharField(max_length=25)),
                ('etnia', models.CharField(max_length=15)),
                ('religiao', models.CharField(max_length=30)),
                ('confirmlgpd', models.BooleanField()),
                ('dthinscricao', models.DateField()),
                ('status', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inscritoconvenio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Laudomed',
            fields=[
                ('idlaudo', models.AutoField(primary_key=True, serialize=False)),
                ('laudodoc', models.BinaryField(blank=True, null=True)),
                ('dthanexo', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'laudomed',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('idmedicamento', models.AutoField(primary_key=True, serialize=False)),
                ('ansiolitico', models.BooleanField(blank=True, null=True)),
                ('antidepressivo', models.BooleanField(blank=True, null=True)),
                ('antipsicotico', models.BooleanField(blank=True, null=True)),
                ('estabhumor', models.BooleanField(blank=True, null=True)),
                ('memoriatct', models.BooleanField(blank=True, null=True)),
                ('outro', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'medicamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Motivoacompanhamento',
            fields=[
                ('idmotivoacamp', models.AutoField(primary_key=True, serialize=False)),
                ('ansiedade', models.BooleanField(blank=True, null=True)),
                ('assediomoral', models.BooleanField(blank=True, null=True)),
                ('depressao', models.BooleanField(blank=True, null=True)),
                ('dfaprendizagem', models.BooleanField(blank=True, null=True)),
                ('humorinstavel', models.BooleanField(blank=True, null=True)),
                ('insonia', models.BooleanField(blank=True, null=True)),
                ('isolasocial', models.BooleanField(blank=True, null=True)),
                ('luto', models.BooleanField(blank=True, null=True)),
                ('tristeza', models.BooleanField(blank=True, null=True)),
                ('apatia', models.BooleanField(blank=True, null=True)),
                ('chorofc', models.BooleanField(blank=True, null=True)),
                ('exaustao', models.BooleanField(blank=True, null=True)),
                ('fadiga', models.BooleanField(blank=True, null=True)),
                ('faltanimo', models.BooleanField(blank=True, null=True)),
                ('vldt', models.BooleanField(blank=True, null=True)),
                ('assediosexual', models.BooleanField(blank=True, null=True)),
                ('outro', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'motivoacompanhamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pcdsnd',
            fields=[
                ('idpcdnd', models.AutoField(primary_key=True, serialize=False)),
                ('tea', models.BooleanField(blank=True, null=True)),
                ('tdah', models.BooleanField(blank=True, null=True)),
                ('dffs', models.BooleanField(blank=True, null=True)),
                ('dfv', models.BooleanField(blank=True, null=True)),
                ('dfa', models.BooleanField(blank=True, null=True)),
                ('ttap', models.BooleanField(blank=True, null=True)),
                ('ahst', models.BooleanField(blank=True, null=True)),
                ('outro', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pcdsnd',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prontuario',
            fields=[
                ('idprontuario', models.AutoField(primary_key=True, serialize=False)),
                ('tcle', models.BinaryField()),
                ('dthprontuario', models.DateTimeField()),
                ('status', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'prontuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Resptec',
            fields=[
                ('idresptec', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('senha', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('crpresp', models.IntegerField(unique=True)),
                ('dthresp', models.DateTimeField()),
                ('emailinst', models.CharField(max_length=255)),
                ('status', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'resptec',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('idsala', models.AutoField(primary_key=True, serialize=False)),
                ('numsala', models.IntegerField()),
                ('tiposala', models.CharField(max_length=10)),
                ('capacidade', models.IntegerField()),
                ('dthsala', models.DateTimeField()),
                ('status', models.BooleanField()),
            ],
            options={
                'db_table': 'sala',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Salaagendamento',
            fields=[
                ('idsolicitacoes', models.AutoField(primary_key=True, serialize=False)),
                ('dthsolisup', models.DateTimeField(blank=True, null=True)),
                ('dthsoliest', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'salaagendamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('idsecretaria', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('codfuncionario', models.IntegerField(unique=True)),
                ('senha', models.CharField(max_length=255)),
                ('dthsec', models.DateTimeField()),
                ('emailinst', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'secretaria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Soliarquivamento',
            fields=[
                ('idsloicitacao', models.AutoField(primary_key=True, serialize=False)),
                ('dthsoliestagiario', models.DateTimeField(blank=True, null=True)),
                ('confirmsup', models.BooleanField(blank=True, null=True)),
                ('dthsolisup', models.DateTimeField(blank=True, null=True)),
                ('confirmresp', models.BooleanField(blank=True, null=True)),
                ('confirmcoord', models.BooleanField(blank=True, null=True)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'soliarquivamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('idsupervisor', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('crp', models.IntegerField(unique=True)),
                ('senha', models.CharField(blank=True, max_length=255, null=True)),
                ('emailinst', models.CharField(blank=True, max_length=255, null=True)),
                ('dthsup', models.DateTimeField()),
                ('status', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'supervisor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipoterapia',
            fields=[
                ('idtipoterapia', models.AutoField(primary_key=True, serialize=False)),
                ('individualift', models.BooleanField(blank=True, null=True)),
                ('individualadt', models.BooleanField(blank=True, null=True)),
                ('individualadto', models.BooleanField(blank=True, null=True)),
                ('individualids', models.BooleanField(blank=True, null=True)),
                ('familia', models.BooleanField(blank=True, null=True)),
                ('grupo', models.BooleanField(blank=True, null=True)),
                ('casal', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tipoterapia',
                'managed': False,
            },
        ),
    ]
